/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        light: '#e8e0d4',
        mind: '#c4a882',
        heart: '#d4856a',
        soul: '#8a9e7a',
        muted: '#a89478',
        bg: '#111318',
        surface: '#1a1d24',
        border: '#2a2d34',
        aurora: '#f0c674',
        zenite: '#e8e0d4',
        crepusculo: '#8a6e5a',
        'mod-purpose': '#c4a882',
        'mod-work': '#8a9e7a',
        'mod-family': '#d4856a',
        'mod-body': '#b8c4a8',
        'mod-mind': '#a89478',
        'mod-bridge': '#8a8a8a',
        'mod-finance': '#7a9e8a',
        'mod-social': '#9e7a8a',
        'mod-soul': '#8a6e5a',
        'stage-1': '#6b6b6b',
        'stage-2': '#8a9e7a',
        'stage-3': '#7a8fb8',
        'stage-4': '#c4a882',
        'stage-5': '#b8896a',
        'stage-6': '#9e7ab8',
        'stage-7': '#d4b872',
      },
      fontFamily: {
        serif: ['Cormorant Garamond', 'serif'],
        sans: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
    },
  },
  plugins: [],
};
